pipelines:
  default:
    - parallel:
      - step:
          name: CI Python 3.6
          image: python:3.10
          caches:
            - pip
          script:
            - make config
            - make create-env
            - make ci

      - step:
          name: CI Python 3.7
          image: python:3.10
          caches:
            - pip
          script:
            - make config
            - make create-env
            - make ci

      - step:
          name: CI Python 3.8
          image: python:3.10
          caches:
            - pip
          script:
            - make config
            - make create-env
            - make ci

      - step:
          name: CI Python 3.9
          image: python:3.10
          caches:
            - pip
          script:
            - make config
            - make create-env
            - make ci