version: '3'

services:

    # MySQL Container
    db:
        image: 'mysql:5.7'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=bestseller
            - MYSQL_USER=bestseller
            - MYSQL_PASSWORD=secret
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        restart: unless-stopped
        healthcheck:
            test: '/usr/bin/mysql --user=bestseller --password=secret --execute "SHOW DATABASES;"'
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - db_data:/var/lib/mysql

    # Web App Container
    app:
        image: "clivern/bestseller:1.0.0"
        build: .
        command: 'gunicorn --bind 0.0.0.0:8000 app.wsgi'
        entrypoint: /entrypoint.sh
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=bestseller
            - DB_USERNAME=bestseller
            - DB_PASSWORD=secret
            - AWS_S3_ACCESS_KEY=
            - AWS_S3_SECRET_KEY=
            - AWS_S3_REGION_NAME=us-east-1
            - AWS_S3_ENDPOINT_URL=https://nyc3.digitaloceanspaces.com
            - AWS_S3_BUCKET_NAME=bestseller
            - AWS_S3_IMPORT_PATH=partners-files
            - AWS_S3_OUTPUT_PATH=bestseller-files
            - ENABLE_AWS_S3_POLLING=true
        volumes:
            - 'app_storage:/app/storage'
        depends_on:
            - db
        ports:
            - '8000:8000'
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/_health"]
            interval: 10s
            timeout: 5s
            retries: 5

    # Daemon Container
    daemon:
        image: "clivern/bestseller:1.0.0"
        build: .
        command: 'python manage.py daemon'
        entrypoint: /entrypoint.sh
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=bestseller
            - DB_USERNAME=bestseller
            - DB_PASSWORD=secret
            - AWS_S3_ACCESS_KEY=
            - AWS_S3_SECRET_KEY=
            - AWS_S3_REGION_NAME=us-east-1
            - AWS_S3_ENDPOINT_URL=https://nyc3.digitaloceanspaces.com
            - AWS_S3_BUCKET_NAME=bestseller
            - AWS_S3_IMPORT_PATH=partners-files
            - AWS_S3_OUTPUT_PATH=bestseller-files
            - ENABLE_AWS_S3_POLLING=true
        volumes:
            - 'daemon_storage:/app/storage'
        depends_on:
            - db
        restart: unless-stopped

volumes:
    db_data: null
    app_storage: null
    daemon_storage: null
