# Generated by Django 3.1.4 on 2021-02-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=100, verbose_name='UUID')),
                ('status', models.CharField(choices=[
                    ('pending', 'PENDING'),
                    ('failed', 'FAILED'),
                    ('succeeded', 'SUCCEEDED'),
                    ('error', 'ERROR')
                ], default='pending', max_length=20, verbose_name='Status')),
                ('payload', models.TextField(verbose_name='Payload')),
                ('result', models.TextField(verbose_name='Result')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'db_table': 'app_task',
            },
        ),
    ]
